# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d941a8d2e8251cd7e6df14ce1d6139c6063d94ed7caf25afe51377ed3cfcb8e2438a2c53487eb63da436c95076600213949b70cf830bc43d645eba09f25ee26a

test:
  secret_key_base: 0cc8bd89542915c809b04d4b8fcf274a1c8005b5a3400f7c3dfaaeaf09847018ddbc946d0d98bcc5089ece60d0b28b98a234b8dc6e94237a8c5ef79f474df661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
